version: "3.8"
services:
  #name for container
  server: 
    image: server
    container_name: ${NAME}
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - UID=${UID}
      - GID=${GID}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    restart: always
    volumes:
      - /home/kln735/Application_with_DB/server/configuration.json:/app/configuration.json
    healthcheck:
      test: ["CMD-SHELL", "/app/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
