version: "3.8"
services:
  #name for container
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${PORT}
    environment:
      - GID=${GID}
      - UID=${UID}
      - TZ=${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    restart: always
    volumes:
      - ./configuration.json:/app/configuration.json
    healthcheck:
      test: ["CMD-SHELL", "/app/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
